/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as DemosRouteImport } from './routes/demos'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as DemosIndexRouteImport } from './routes/demos.index'
import { Route as PlayersSteamIdRouteImport } from './routes/players.$steamId'
import { Route as DemosDemoIdRouteImport } from './routes/demos.$demoId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayersRoute,
} as any)
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemosRoute,
} as any)
const PlayersSteamIdRoute = PlayersSteamIdRouteImport.update({
  id: '/$steamId',
  path: '/$steamId',
  getParentRoute: () => PlayersRoute,
} as any)
const DemosDemoIdRoute = DemosDemoIdRouteImport.update({
  id: '/$demoId',
  path: '/$demoId',
  getParentRoute: () => DemosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demos': typeof DemosRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/players/$steamId': typeof PlayersSteamIdRoute
  '/demos/': typeof DemosIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/settings': typeof SettingsRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/players/$steamId': typeof PlayersSteamIdRoute
  '/demos': typeof DemosIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demos': typeof DemosRouteWithChildren
  '/players': typeof PlayersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/players/$steamId': typeof PlayersSteamIdRoute
  '/demos/': typeof DemosIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/demos'
    | '/players'
    | '/settings'
    | '/demos/$demoId'
    | '/players/$steamId'
    | '/demos/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/settings'
    | '/demos/$demoId'
    | '/players/$steamId'
    | '/demos'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/demos'
    | '/players'
    | '/settings'
    | '/demos/$demoId'
    | '/players/$steamId'
    | '/demos/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DemosRoute: typeof DemosRouteWithChildren
  PlayersRoute: typeof PlayersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/demos/': {
      id: '/demos/'
      path: '/'
      fullPath: '/demos/'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof DemosRoute
    }
    '/players/$steamId': {
      id: '/players/$steamId'
      path: '/$steamId'
      fullPath: '/players/$steamId'
      preLoaderRoute: typeof PlayersSteamIdRouteImport
      parentRoute: typeof PlayersRoute
    }
    '/demos/$demoId': {
      id: '/demos/$demoId'
      path: '/$demoId'
      fullPath: '/demos/$demoId'
      preLoaderRoute: typeof DemosDemoIdRouteImport
      parentRoute: typeof DemosRoute
    }
  }
}

interface DemosRouteChildren {
  DemosDemoIdRoute: typeof DemosDemoIdRoute
  DemosIndexRoute: typeof DemosIndexRoute
}

const DemosRouteChildren: DemosRouteChildren = {
  DemosDemoIdRoute: DemosDemoIdRoute,
  DemosIndexRoute: DemosIndexRoute,
}

const DemosRouteWithChildren = DemosRoute._addFileChildren(DemosRouteChildren)

interface PlayersRouteChildren {
  PlayersSteamIdRoute: typeof PlayersSteamIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

const PlayersRouteChildren: PlayersRouteChildren = {
  PlayersSteamIdRoute: PlayersSteamIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}

const PlayersRouteWithChildren =
  PlayersRoute._addFileChildren(PlayersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DemosRoute: DemosRouteWithChildren,
  PlayersRoute: PlayersRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
