// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeDemo(arg1:number):Promise<models.Game>;

export function CreateDemo(arg1:string):Promise<models.Demo>;

export function DeleteDemo(arg1:number):Promise<void>;

export function GetDemos():Promise<Array<models.Demo>>;

export function GetGame(arg1:number):Promise<models.Game>;

export function GetPlayerProfile(arg1:string):Promise<models.PlayerProfile>;

export function GetPlayers():Promise<Array<models.PlayerListItem>>;

export function Greet(arg1:string):Promise<string>;

export function SelectDemoFiles():Promise<Array<string>>;

export function SetGameRecordedAt(arg1:number,arg2:number):Promise<void>;

export function SetPlayerName(arg1:string,arg2:string):Promise<void>;

export function UpdateDemo(arg1:number,arg2:string):Promise<models.Demo>;
