// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDemo(arg1) {
  return window['go']['main']['App']['AnalyzeDemo'](arg1);
}

export function CreateDemo(arg1) {
  return window['go']['main']['App']['CreateDemo'](arg1);
}

export function DeleteDemo(arg1) {
  return window['go']['main']['App']['DeleteDemo'](arg1);
}

export function GetDemos() {
  return window['go']['main']['App']['GetDemos']();
}

export function GetGame(arg1) {
  return window['go']['main']['App']['GetGame'](arg1);
}

export function GetPlayerProfile(arg1) {
  return window['go']['main']['App']['GetPlayerProfile'](arg1);
}

export function GetPlayers() {
  return window['go']['main']['App']['GetPlayers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDemoFiles() {
  return window['go']['main']['App']['SelectDemoFiles']();
}

export function SetGameRecordedAt(arg1, arg2) {
  return window['go']['main']['App']['SetGameRecordedAt'](arg1, arg2);
}

export function SetPlayerName(arg1, arg2) {
  return window['go']['main']['App']['SetPlayerName'](arg1, arg2);
}

export function UpdateDemo(arg1, arg2) {
  return window['go']['main']['App']['UpdateDemo'](arg1, arg2);
}
